Document: mypkg
Title: Debian mypkg Manual
Author: <insert document author here>
Abstract: This manual describes what mypkg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mypkg/mypkg.sgml.gz

Format: postscript
Files: /usr/share/doc/mypkg/mypkg.ps.gz

Format: text
Files: /usr/share/doc/mypkg/mypkg.text.gz

Format: HTML
Index: /usr/share/doc/mypkg/html/index.html
Files: /usr/share/doc/mypkg/html/*.html
